package com.zcam.core.logging

enum class LogEventId(val code: String) {
    SERVICE_CREATED("SVC-100"),
    SERVICE_START_REQUESTED("SVC-101"),
    SERVICE_STOP_REQUESTED("SVC-102"),

    RUNTIME_START_SEQUENCE("RUN-100"),
    RUNTIME_STOP_SEQUENCE("RUN-101"),
    RUNTIME_ALREADY_RUNNING("RUN-102"),
    RUNTIME_ALREADY_STOPPED("RUN-103"),

    COMPONENT_STARTING("CMP-100"),
    COMPONENT_HEALTHY("CMP-101"),
    COMPONENT_STOPPING("CMP-102"),
    COMPONENT_STOPPED("CMP-103"),
    COMPONENT_FAILED("CMP-104"),

    WATCHDOG_STARTED("WDG-100"),
    WATCHDOG_STOPPED("WDG-101"),
    WATCHDOG_STALE("WDG-102"),

    RECOVERY_SCHEDULED("REC-100"),
    RECOVERY_ATTEMPT("REC-101"),
    RECOVERY_SUCCEEDED("REC-102"),
    RECOVERY_COOLDOWN("REC-103"),
    RECOVERY_FAILED("REC-104"),

    RECORDING_STARTED("RCD-100"),
    RECORDING_STOPPED("RCD-101"),
    RECORDING_SEGMENT_STARTED("RCD-102"),
    RECORDING_SEGMENT_FINALIZED("RCD-103"),
    RECORDING_SEGMENT_FAILED("RCD-104"),
    RECORDING_CLEANUP_REMOVED("RCD-105"),
    RECORDING_INDEX_REBUILT("RCD-106"),
    RECORDING_INDEX_CORRUPTED("RCD-107"),
    RECORDING_RECOVERY_REQUIRED("RCD-108"),
    RECORDING_CLEANUP_FAILED("RCD-109"),

    STATE_RESTORE_CHECK("RST-100"),
    STATE_RESTORE_START("RST-101"),
    STATE_RESTORE_SKIP("RST-102")
}
